version: 2.0
- command:
   name: runtests
   execute:
      - cd tests/driver
      - ./test_runner
   description: Run Bob unit tests
   flags:
      - unixonly
- command:
   name: debug
   execute:
      - gprbuild -P bob.gpr
   description: Build Bob in debug mode
- command:
   name: release
   execute:
      - gprclean -P bob.gpr
      - gprbuild -p bob.gpr -XMode=release
      - mkdir -p usr/share/doc/bob
      - mkdir -p usr/bin
      - cp bin/bob usr/bin
      - cp README.md usr/share/doc/bob
      - cp COPYING usr/share/doc/bob
      - cp CHANGELOG.md usr/share/doc/bob
      - cp CONTRIBUTING.md usr/share/doc/bob
      - gprclean -P bob.gpr
   description: Build Bob in release mode
   flags:
      - unixonly
- command:
   name: analyze
   execute:
      - gprbuild -P bob.gpr -XMode=analyze
   description: Build Bob in analyze mode
- command:
   name: clean
   execute:
      - gprclean -P bob.gpr
   description: Clean all compilation files
- command:
   name: createtests
   execute:
      - gnattest -P bob.gpr
   description: Regenerate unit tests
- command:
   name: tests
   execute:
      - gprbuild -P tests/driver/test_driver.gpr
   description: Build Bob unit tests
   flags:
      - unixonly
- command:
   name: docs
   execute:
      - others/generatedocs.py
   description: Generate code documentation
   flags:
      - unixonly
- command:
   name: gprof
   execute:
      - gprof bin/bob gmon.out
   description: Generate gprof report
   output: gprof.txt
   flags:
      - unixonly
- command:
   name: windows
   execute:
      - gprclean -P bob.gpr --target=x86_64-windows
      - gprbuild -p -P steamsky.gpr -XMode=release --target=x86_64-windows
      - mkdir -p release/doc/bob
      - mkdir -p release/bin
      - cp bin/bob release/bin
      - cp README.md release/doc/bob
      - cp COPYING release/doc/bob
      - cp CHANGELOG.md release/doc/bob
      - cp CONTRIBUTING.md release/doc/bob
      - gprclean -P bob.gpr --target=x86_64-windows
   description: Build Windows version of Bob on Linux
   flags:
      - unixonly
- command:
   name: release
   execute:
      - gprclean -P bob.gpr
      - gprbuild -P bob.gpr -XMode=release
      - XCOPY /S bin release\
      - XCOPY README.md release\doc\
      - XCOPY COPYING release\doc\
      - XCOPY CHANGELOG.md release\doc\
      - XCOPY CONTRIBUTING.md release\doc\
      - gprclean -P bob.gpr
   description: Build Bob in release mode
   flags:
      - windowsonly
