version: 3.0
- command:
   name: debug
   execute:
      - gprbuild -P bob.gpr
   description: Build Bob in debug mode
- command:
   name: release
   execute:
      - tclsh others/build.tcl
   description: Build Bob in release mode
- command:
   name: analyze
   execute:
      - gprbuild -P bob.gpr -XMode=analyze
   description: Build Bob in analyze mode
- command:
   name: clean
   execute:
      - gprclean -P bob.gpr
   description: Clean all compilation files
- command:
   name: createtests
   execute:
      - gnattest -P bob.gpr
   description: Regenerate unit tests
- command:
   name: tests
   execute:
      - tclsh others/tests.tcl
   description: Build and execute Bob unit tests
   flags:
      - unixpath
- command:
   name: docs
   execute:
      - tclsh others/generatedocs.tcl
   description: Generate code documentation
   flags:
      - unixpath
- command:
   name: gprof
   execute:
      - gprof bin/bob gmon.out
   description: Generate gprof report
   output: gprof.txt
   flags:
      - unixpath
- command:
   name: windows
   execute:
      - sudo docker run --rm -w /app -v $1:/app ghcr.io/thindil/adabuildwin64 /bin/bash others/build.tcl x86_64-windows
   description: Build Windows version of Bob on Linux, required argument is full path to the project
   flags:
      - unixonly
- command:
   name: pretty
   execute:
      - gnatpp -P bob.gpr
      - gnatpp -P tests/prettytests.gpr
   description: Pretty print Bob source code
- command:
   name: push
   execute:
      - fossil push
      - fossil git export
   description: Update remote Fossil repository and its Git mirror
- command:
   name: check
   execute:
      - gprclean -P bob.gpr
      - cd obj
      - adactl -f ../others/rules.aru -p ../bob.gpr -r bob
   description: Run AdaControl to check correctness of the code
   flags:
      - unixpath
- command:
   name: checkall
   execute:
      - bob debug
      - bob tests
      - bob check
   description: Run all the project tests
- command:
   name: checkfile
   execute:
      - gprclean -P bob.gpr
      - cd obj
      - adactl -f ../others/rules.aru -p ../bob.gpr ../src/$1
   description: Run AdaControl to check correctness of the selected file
   flags:
      - unixpath
