version: 3.0
- command:
   name: debug
   execute:
      - gprbuild -P bob.gpr
   description: Build Bob in debug mode
- command:
   name: release
   execute:
      - gprclean -P bob.gpr
      - gprbuild -p bob.gpr -XMode=release
      - mkdir -p usr/share/doc/bob
      - mkdir -p usr/bin
      - cp bin/bob usr/bin
      - cp README.md usr/share/doc/bob
      - cp COPYING usr/share/doc/bob
      - cp CHANGELOG.md usr/share/doc/bob
      - cp CONTRIBUTING.md usr/share/doc/bob
      - gprclean -P bob.gpr
   description: Build Bob in release mode
   flags:
      - unixonly
- command:
   name: analyze
   execute:
      - gprbuild -P bob.gpr -XMode=analyze
   description: Build Bob in analyze mode
- command:
   name: clean
   execute:
      - gprclean -P bob.gpr
   description: Clean all compilation files
- command:
   name: createtests
   execute:
      - gnattest -P bob.gpr
   description: Regenerate unit tests
- command:
   name: tests
   execute:
      - tclsh others/tests.tcl
   description: Build and execute Bob unit tests
   flags:
      - unixpath
- command:
   name: docs
   execute:
      - tclsh others/generatedocs.tcl
   description: Generate code documentation
   flags:
      - unixpath
- command:
   name: gprof
   execute:
      - gprof bin/bob gmon.out
   description: Generate gprof report
   output: gprof.txt
   flags:
      - unixpath
- command:
   name: windows
   execute:
      - gprclean -P bob.gpr --target=x86_64-windows
      - gprbuild -p -P steamsky.gpr -XMode=release --target=x86_64-windows
      - mkdir -p release/doc/bob
      - mkdir -p release/bin
      - cp bin/bob release/bin
      - cp README.md release/doc/bob
      - cp COPYING release/doc/bob
      - cp CHANGELOG.md release/doc/bob
      - cp CONTRIBUTING.md release/doc/bob
      - gprclean -P bob.gpr --target=x86_64-windows
   description: Build Windows version of Bob on Linux
   flags:
      - unixonly
- command:
   name: release
   execute:
      - gprclean -P bob.gpr
      - gprbuild -P bob.gpr -XMode=release
      - XCOPY /S bin release\
      - XCOPY README.md release\doc\
      - XCOPY COPYING release\doc\
      - XCOPY CHANGELOG.md release\doc\
      - XCOPY CONTRIBUTING.md release\doc\
      - gprclean -P bob.gpr
   description: Build Bob in release mode
   flags:
      - windowsonly
- command:
   name: pretty
   execute:
      - gnatpp -P bob.gpr
      - gnatpp -P tests/prettytests.gpr
   description: Pretty print Bob source code
- command:
   name: push
   execute:
      - fossil push
      - fossil git export
   description: Update remote Fossil repository and its Git mirror
- command:
   name: check
   execute:
      - gprclean -P bob.gpr
      - cd obj
      - adactl -f ../others/rules.aru -p ../bob.gpr -r bob
   description: Run AdaControl to check correctness of the code
   flags:
      - unixpath
