- command:
   name: runtests
   execute: cd tests/driver && ./test_runner
   description: Run Bob unit tests
- command:
   name: debug
   execute: gprbuild -P bob.gpr
   description: Build Bob in debug mode
