- command:
   name: runtests
   execute:
      - cd tests/driver
      - ./test_runner
   description: Run Bob unit tests
- command:
   name: debug
   execute:
      - gprbuild -P bob.gpr
   description: Build Bob in debug mode
- command:
   name: release
   variables:
      - releasedir = usr
   execute:
      - gprclean -P bob.gpr
      - gprbuild -p bob.gpr -XMode=release
      - mkdir -p $releasedir/share/doc
      - mkdir -p $releasedir/bin
      - cp bin/bob $releasedir/bin
      - cp README.md $releasedir/share/doc
      - cp COPYING $releasedir/share/doc
      - cp CHANGELOG.md $releasedir/share/doc
      - cp CONTRIBUTING.md $releasedir/share/doc
      - gprclean -P bob.gpr
   description: Build Bob in release mode
- command:
   name: analyze
   execute:
      - gprbuild -P bob.gpr -XMode=analyze
   description: Build Bob in analyze mode
- command:
   name: clean
   execute:
      - gprclean -P bob.gpr
   description: Clean all compilation files
- command:
   name: createtests
   execute:
      - gnattest -P bob.gpr
   description: Regenerate unit tests
- command:
   name: tests
   execute:
      - gprbuild -P tests/driver/test_driver.gpr
   description: Build Bob unit tests
- command:
   name: docs
   execute:
      - others/generatedocs.py
   description: Generate code documentation
- command:
   name: gprof
   execute:
      - gprof bin/bob gmon.out
   description: Generate gprof report
- command:
   name: windows
   execute:
      - wineconsole others/build.cmd
   description: Build Windows version of Bob on Linux
