name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:

  tests:

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuild

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Style check
      run: |
         gprbuild -P bob.gpr
         gprclean -P bob.gpr

    - name: Generate tests
      run: gnattest -P bob.gpr

    - name: Build and run the tests
      run: others/tests.tcl

    - name: Run AdaControl static analysis
      run: |
         gprclean -P bob.gpr
         cd obj
         adactl -f ../others/rules.aru -p ../bob.gpr -o ../adacontrol.log -r bob
         cd ..

  build_linux:

    needs: tests

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuild

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the program
      run: |
         gprbuild -p -P bob.gpr -XMode=release
         mkdir -p usr/share/doc/bob
         mkdir -p usr/bin
         cp bin/bob usr/bin
         cp README.md usr/share/doc/bob
         cp COPYING usr/share/doc/bob
         cp CHANGELOG.md usr/share/doc/bob
         cp CONTRIBUTING.md usr/share/doc/bob

    - name: Compress the artifact
      run: tar -cf bob-linux.tar usr

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
         name: bob-linux.tar
         path: bob-linux.tar

  build_windows:

    needs: tests

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuildwin64

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the program
      run: |
         gprbuild -p -P bob.gpr -XMode=release --target=x86_64-windows
         mkdir -p bin/doc
         cp README.md bin/doc
         cp COPYING bin/doc
         cp CHANGELOG.md bin/doc
         cp CONTRIBUTING.md bin/doc

    - name: Compress the artifact
      run: tar -cf bob-windows.tar bin

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
         name: bob-windows.tar
         path: bob-windows.tar
