name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:

  tests:

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuild:9

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Style check
      run: |
         gprbuild -P bob.gpr
         gprclean -P bob.gpr

    - name: Generate tests
      run: gnattest -P bob.gpr

    - name: Build and run the tests
      run: others/tests.tcl

    - name: Run AdaControl static analysis
      run: |
         gprclean -P bob.gpr
         cd obj
         adactl -f ../others/rules.aru -p ../bob.gpr -o ../adacontrol.log -r bob
         cd ..

  build_linux:

    needs: tests

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuild:9

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the program
      run: others/build.tcl

    - name: Compress the artifact
      run: tar -cf bob-linux.tar usr

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
         name: bob-linux.tar
         path: bob-linux.tar

  build_windows:

    needs: tests

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuildwin64:9

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the program
      run: others/build.tcl x86_64-windows

    - name: Compress the artifact
      run: tar -cf bob-windows.tar release

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
         name: bob-windows.tar
         path: bob-windows.tar

  build_raspberry_pi:

    needs: tests

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuildraspi:9

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the program
      run: others/build.tcl arm-linux-gnueabihf

    - name: Compress the artifact
      run: tar -cf bob-raspberrypi.tar usr

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
         name: bob-raspberrypi.tar
         path: bob-raspberrypi.tar

